### ISSUE TITLE
Best Fuzzer

### ISSUE THREAD

**Issue by thefaeriedragon** [Iljalala/AdvancedWebFuzzer#1]
Лучший фазер что я когда либо видел. Поражает точность и скорость работы. Планируете ли коммерческую версию?

**Comment by Iljalala** [comment]
Спасибо за отзыв!

Да, планируем сделать, но перед этим я думаю мы выйдем на ICO и внедрим машинное обучение. Это будет лучший сканер для Security Resilience Experts.

**Comment by ttffdd** [comment]
Когда уже купить можно будет? У меня есть на примете одна компания заинтересованная

**Comment by barrracud4** [comment]
> Когда уже купить можно будет? У меня есть на примете одна компания заинтересованная

Думаю что уже сегодня. Стоимость покупки - одна слойка.
